import AppLayout from '@/layouts/app-layout'
import { BreadcrumbItem } from '@/types'
import { useTranslation } from 'react-i18next'
import StoreCategoryForm from './components/store-category-form'
import { StoreCategory } from '@/types/dashboard'

// Routes will be auto-generated by wayfinder
const storeCategoryRoutes = {
    index: { url: () => '/admin/store-categories' },
    create: { url: () => '/admin/store-categories/create' },
}

const StoreCategoriesCreate = ({ category }: { category: StoreCategory }) => {
    const { t } = useTranslation('dashboard');

    const breadcrumbs: BreadcrumbItem[] = [
        {
            title: t('store_categories.title'),
            href: storeCategoryRoutes.index.url(),
        },
        {
            title: t('store_categories.create'),
            href: storeCategoryRoutes.create.url(),
        },
    ]

    return (
        <AppLayout breadcrumbs={breadcrumbs} title={t('store_categories.create')}>
            <StoreCategoryForm category={category} type="create" />
        </AppLayout>
    )
}

export default StoreCategoriesCreate

