import { Form, router } from '@inertiajs/react'
import {
    Card,
    CardContent,
    CardDescription,
    CardFooter,
    CardHeader,
    CardTitle,
} from '@/components/ui/card'
import { Locale, Store, StoreCategory } from '@/types/dashboard'
import FormButtons from '@/components/form/form-buttons'
import TranslatableFieldsCard from '@/components/form/translatable-tabs'
import { normalizeFieldValue } from '@/lib/utils'


// Routes will be auto-generated by wayfinder
const storeRoutes = {
    index: { url: () => '/admin/stores' },
    store: { url: () => '/admin/stores' },
    update: { url: (args: { store: string | number }) => `/admin/stores/${args.store}` },
}

interface StoreFormProps {
    store: Store
    categories: StoreCategory[]
    type: 'create' | 'edit'
}

export default function StoreForm({ store, categories, type }: StoreFormProps) {
    return (
        <Form
            method={type === 'edit' ? 'put' : 'post'}
            action={
                (type === 'edit' && store.id)
                    ? storeRoutes.update.url({ store: store.id })
                    : storeRoutes.store.url()
            }
        >
            {({ processing, errors }) => (
                <>
                    <div className="flex flex-col gap-4 max-w-2xl">
                        <TranslatableFieldsCard
                            title="Store Content"
                            fields={[
                                { key: 'name', label: 'Name', type: 'input', value: normalizeFieldValue(store.name) },
                                { key: 'description', label: 'Description', type: 'textarea', value: normalizeFieldValue(store.description) },
                                { key: 'address', label: 'Address', type: 'input', value: normalizeFieldValue(store.address) },
                            ]}
                        />
                    </div>

                    <FormButtons
                        processing={processing}
                        handleCancel={() => router.visit(storeRoutes.index.url())}
                        isEditMode={type === 'edit'}
                    />
                </>
            )}
        </Form>
    )
}

