import { Form, router } from '@inertiajs/react'
import { useState } from 'react'
import {
    Card,
    CardContent,
    CardDescription,
    CardFooter,
    CardHeader,
    CardTitle,
} from '@/components/ui/card'
import { Field, Locale, Store, StoreCategory } from '@/types/dashboard'
import FormButtons from '@/components/form/form-buttons'
import TranslatableFieldsCard from '@/components/form/translatable-tabs'
import { normalizeFieldValue } from '@/lib/utils'
import AlertError from '@/components/alert-error'
import FormInput from '@/components/form/form-input'
import { LocalizedInputCard } from '@/components/form/test';
import TranslatableTabs from '@/components/form/translatable-tabs'
import { Label } from '@/components/ui/label'
import { Input } from '@/components/ui/input'
import InputError from '@/components/input-error'
import {
    Select,
    SelectContent,
    SelectItem,
    SelectTrigger,
    SelectValue,
} from '@/components/ui/select'
import IsActive from '@/components/form/is-active'
import FileUpload from '@/components/form/file-upload'


// Routes will be auto-generated by wayfinder
const storeRoutes = {
    index: { url: () => '/admin/stores' },
    store: { url: () => '/admin/stores' },
    update: { url: (args: { store: string | number }) => `/admin/stores/${args.store}` },
}

interface StoreFormProps {
    store: Store;
    categories: StoreCategory[];
    type: 'create' | 'edit';
}

export default function StoreForm({ store, categories, type }: StoreFormProps) {
    console.log(store);

    return (
        <Form
            method={type === 'edit' ? 'put' : 'post'}
            action={
                (type === 'edit' && store.id)
                    ? storeRoutes.update.url({ store: store.id })
                    : storeRoutes.store.url()
            }
        >
            {({ processing, errors }) => (
                <>
                    <div className="space-y-6 lg:grid lg:grid-cols-3 lg:gap-6 lg:space-y-0">
                        {/* Left column – main translatable fields */}
                        <div className="lg:col-span-2 space-y-6">
                            <TranslatableTabs
                                fields={[
                                    {
                                        name: 'name',
                                        label: 'Name',
                                        type: 'text',
                                        value: normalizeFieldValue(store.name),
                                        placeholder: 'Enter name',
                                    },
                                    {
                                        name: 'description',
                                        label: 'Description',
                                        type: 'textarea',
                                        value: normalizeFieldValue(store.description),
                                    },
                                    {
                                        name: 'address',
                                        label: 'Address',
                                        type: 'text',
                                        value: normalizeFieldValue(store.address),
                                        placeholder: 'Enter address',
                                    },
                                ]}
                                errors={errors}
                            />

                            <Card>
                                <CardHeader>
                                    <CardTitle>Category</CardTitle>
                                    <CardDescription>
                                        Select a category for this store
                                    </CardDescription>
                                </CardHeader>
                                <CardContent>
                                    <div>
                                        <Label htmlFor="category_id">Store Category</Label>
                                        <Select
                                            defaultValue={String(store.category_id)}
                                            name='category_id'
                                        >
                                            <SelectTrigger id="category_id" aria-invalid={errors.category_id ? 'true' : 'false'}>
                                                <SelectValue defaultValue={String(store.category_id)} />
                                            </SelectTrigger>
                                            <SelectContent>
                                                <SelectItem value="null" disabled>No category</SelectItem>
                                                {categories.map((category) => (
                                                    <SelectItem
                                                        key={category.id}
                                                        value={String(category.id)}
                                                    >
                                                        {category.name as string}
                                                    </SelectItem>
                                                ))}
                                            </SelectContent>
                                        </Select>
                                        <InputError message={errors.category_id} />
                                    </div>
                                </CardContent>
                            </Card>


                            <Card>
                                <CardHeader>
                                    <CardTitle>Store Images</CardTitle>
                                    <CardDescription>
                                        Upload store logo and gallery images
                                    </CardDescription>
                                </CardHeader>
                                <CardContent className="space-y-4">
                                    <FileUpload
                                        name="logo_temp_id"
                                        label="Store Logo"
                                        multiple={true}
                                        required
                                        acceptedFileTypes={['image/*']}
                                        maxFiles={1}
                                        maxFileSize="5MB"
                                        error={errors.temp_ids}
                                        files={store.logo ? store.logo.map((logo) => ({
                                            source: String(logo.id) + '/' + logo.file_name,
                                            options: {
                                                type: 'local',
                                            },
                                        })) : []}
                                    />
                                </CardContent>
                            </Card>
                        </div>

                        {/* Right column – credentials & settings */}
                        <div className="space-y-6">
                            <Card>
                                <CardHeader>
                                    <CardTitle>Store Credentials</CardTitle>
                                </CardHeader>
                                <CardContent className="space-y-4">
                                    <div>
                                        <Label htmlFor="email">Email</Label>
                                        <Input
                                            id="email"
                                            name="email"
                                            type="email"
                                            required
                                            defaultValue={store.email}
                                            placeholder="Enter email address"
                                            aria-invalid={errors.email ? 'true' : 'false'}
                                        />
                                        <InputError message={errors.email} />
                                    </div>

                                    <div>
                                        <Label htmlFor="password">Password</Label>
                                        <Input
                                            id="password"
                                            name="password"
                                            type="password"
                                            required={type === 'create'}
                                            aria-invalid={errors.password ? 'true' : 'false'}
                                        />
                                        <span className="text-muted-foreground text-xs">
                                            {type === 'create'
                                                ? 'Enter password (min. 8 characters)'
                                                : 'Leave blank to keep current'}
                                        </span>
                                        <InputError message={errors.password} />
                                    </div>
                                </CardContent>
                            </Card>

                            <Card>
                                <CardHeader>
                                    <CardTitle>Store Settings</CardTitle>
                                </CardHeader>
                                <CardContent className="space-y-4">
                                    <div>
                                        <Label htmlFor="phone">Phone Number</Label>
                                        <Input
                                            id="phone"
                                            name="phone"
                                            type="text"
                                            required
                                            defaultValue={store.phone}
                                            aria-invalid={errors.phone ? 'true' : 'false'}
                                        />
                                        <InputError message={errors.phone} />
                                    </div>
                                    <div>
                                        <Label htmlFor="delivery_time">Delivery Time</Label>
                                        <Input
                                            id="delivery_time"
                                            name="delivery_time"
                                            type="number"
                                            defaultValue={store.delivery_time}
                                            aria-invalid={errors.delivery_time ? 'true' : 'false'}
                                        />
                                        <span className="text-muted-foreground text-xs">
                                            Enter delivery time in minutes
                                        </span>
                                        <InputError message={errors.delivery_time} />
                                    </div>

                                    <IsActive value={store.is_active ?? true} />
                                </CardContent>
                            </Card>
                        </div>
                    </div>

                    <FormButtons
                        processing={processing}
                        handleCancel={() => router.visit(storeRoutes.index.url())}
                        isEditMode={type === 'edit'}
                    />
                </>
            )}
        </Form>
    )
}

