import {
    Popover,
    PopoverContent,
    PopoverTrigger,
} from "@/components/ui/popover"
import {
    Command,
    CommandEmpty,
    CommandGroup,
    CommandInput,
    CommandItem,
    CommandList,
    CommandSeparator,
} from "@/components/ui/command"
import { useState } from "react";
import { router } from "@inertiajs/react";
import { Check, Filter } from "lucide-react";
import { Badge } from "@/components/ui/badge";

// Routes will be auto-generated by wayfinder
const storeRoutes = {
    index: {
        url: () => '/admin/stores',
        get: (options?: any) => ({
            url: '/admin/stores' + (options?.url || ''),
            method: 'get' as const,
        }),
    },
}

export default function StoresFilters() {
    const url = new URL(window.location.href);
    const [filters, setFilters] = useState<Record<string, string | undefined>>({
        is_active: url.searchParams.get('is_active') || undefined,
        category_id: url.searchParams.get('category_id') || undefined
    });

    const onChange = (key: string, value: string | undefined) => {
        setFilters({ ...filters, [key]: value });

        router.get(storeRoutes.index.get({
            mergeQuery: {
                [key]: value,
                page: 1,
            },
        }).url, {}, {
            preserveState: true,
            preserveScroll: true,
        });
    }

    const resetFilters = () => {
        setFilters({});
        router.get(storeRoutes.index.url(), {}, {
            preserveState: true,
            preserveScroll: true,
        });
    }

    return (
        <>
            <Popover>
                <PopoverTrigger asChild>
                    <button className="px-2 py-1 border rounded flex items-center gap-2">
                        <Filter size={14} /> Status
                        {
                            filters.is_active !== undefined && (
                                <Badge variant="secondary">{filters.is_active === "1" ? "Active" : "Inactive"}</Badge>
                            )
                        }
                    </button>
                </PopoverTrigger>

                <PopoverContent className="w-56 p-0">
                    <Command>
                        <CommandInput placeholder={`Filter by Status...`} />
                        <CommandList>
                            <CommandEmpty>No results found.</CommandEmpty>
                            <CommandGroup>
                                {
                                    [
                                        { value: undefined, label: "All" },
                                        { value: "1", label: "Active" },
                                        { value: "0", label: "Inactive" },
                                    ].map((opt) => {
                                        const isSelected = filters.is_active === opt.value
                                        return (
                                            <CommandItem
                                                key={opt.value}
                                                onSelect={() => onChange("is_active", opt.value)}
                                            >
                                                <div
                                                    className={`mr-2 flex h-4 w-4 items-center justify-center rounded border ${isSelected ? "bg-primary text-primary-foreground" : "bg-transparent"
                                                        }`}
                                                >
                                                    {isSelected && <Check size={12} />}
                                                </div>
                                                {opt.label}
                                            </CommandItem>
                                        )
                                    })}
                            </CommandGroup>
                        </CommandList>

                        {filters.is_active !== undefined && (
                            <>
                                <CommandSeparator />
                                <div
                                    className="p-2 text-center text-sm cursor-pointer"
                                    onClick={() => onChange("is_active", undefined)}
                                >
                                    Clear Status
                                </div>
                            </>
                        )}
                    </Command>
                </PopoverContent>
            </Popover>
        </>
    );
}

